paths:
  eeg_data: "data/raw/eeg"
  events: "data/raw/events"
  metadata: "data/raw/metadata"
  physio: "data/raw/metadata"
  subjective: "data/raw/subjective"
  raw_data: "data/raw/metadata"
  filtered_eeg: "data/eeg/filtered"
  cleaned_eeg: "output/cleaned_eeg"
  output: "output"
  logs: "output/logs"
  results: "results"
  scripts: "scripts"
  vis: "output/eeg_visualisations" 
  eeg_qc: "output/qc/eeg"
  physio_qc: "output/qc/physio"
  failed_qc: "output/qc/summary"
  counterbalance: "data"
  xgb_results: "results/xgb/results"
  xgb_bayes: "results/xgb/bayes_opt"
  init_pruned: "results/xgb/init_pruned"
