channel_names:
  - Z2
  - Z4
  - Z6
  - Z8
  - Z10
  - Z12
  - L1
  - L2
  - L3
  - L4
  - L5
  - L6
  - L7
  - L8
  - L9
  - L10
  - L11
  - L12
  - L13
  - L14
  - LL1
  - LL2
  - LL3
  - LL4
  - LL5
  - LL6
  - LL7
  - LL8
  - LL9
  - LL10
  - LL11
  - LL12
  - Z1
  - Z3
  - Z5
  - Z9
  - Z11
  - Z13
  - R1
  - R2
  - R3
  - R4
  - R5
  - R6
  - R7
  - R8
  - R9
  - R10
  - R11
  - R12
  - R13
  - R14
  - RR1
  - RR2
  - RR3
  - RR4
  - RR5
  - RR6
  - RR7
  - RR8
  - RR9
  - RR10
  - RR11
  - RR12
  - LL13
  - LL14
  - LA1
  - LA2
  - LA3
  - LA4
  - LA5
  - LB1
  - LB2
  - LB3
  - LB4
  - LB5
  - LB6
  - LC1
  - LC2
  - LC3
  - LC4
  - LC5
  - LC6
  - LC7
  - LD1
  - LD2
  - LD3
  - LD4
  - LD5
  - LD6
  - LD7
  - LE1
  - LE2
  - LE3
  - LE4
  - Lm
  - RR13
  - RR14
  - RA1
  - RA2
  - RA3
  - RA4
  - RA5
  - RB1
  - RB2
  - RB3
  - RB4
  - RB5
  - RB6
  - RC1
  - RC2
  - RC3
  - RC4
  - RC5
  - RC6
  - RC7
  - RD1
  - RD2
  - RD3
  - RD4
  - RD5
  - RD6
  - RD7
  - RE1
  - RE2
  - RE3
  - RE4
  - RM
