participant_id: 8

paths:
  eeg_data:      "data/raw/eeg"
  events:        "data/raw/events"
  metadata:      "data/raw/metadata"
  physio:        "data/raw/metadata"
  subjective:    "data/raw/subjective"
  raw_data:      "data/raw/metadata"
  filtered_eeg:  "data/eeg/filtered"
  cleaned_eeg:   "output/cleaned_eeg"
  output:        "output"
  logs:          "output/logs"
  results:       "results"
  scripts:       "scripts"
  vis:           "output/eeg_visualisations" 
  eeg_qc:        "output/qc/eeg"
  physio_qc:     "output/qc/physio"
  failed_qc:     "output/qc/summary"
  counterbalance: "data"
  xgb_results:   "results/xgb/results"
  xgb_bayes:     "results/xgb/bayes_opt"
  init_pruned:   "results/xgb/init_pruned"

canonical_features:
  - hrv_rmssd
  - hr_heartrate_bpm_med_abs
  - gsr_skin_conductance_eda_tonic_mean_nk
  - gsr_skin_conductance_eda_pkht_mean_nk
  - eeg_fm_theta_mean
  - eeg_f_beta_mean
  - eeg_p_alpha_mean
  - pupil_dilation_med

pretty_features:
  hrv_rmssd: "HRV RMSSD"
  hr_heartrate_bpm_med_abs: "Heart Rate (Median BPM)"
  gsr_skin_conductance_eda_tonic_mean_nk: "EDA Tonic"
  gsr_skin_conductance_eda_pkht_mean_nk: "EDA Peak Height"
  eeg_fm_theta_mean: "EEG FM Theta"
  eeg_f_beta_mean: "EEG Beta"
  eeg_p_alpha_mean: "EEG Parietal Alpha"
  pupil_dilation_med: "Pupil Dilation"

feature_order:
  - HRV RMSSD
  - Heart Rate (Median BPM)
  - EDA Tonic
  - EDA Peak Height
  - Pupil Dilation
  - EEG FM Theta
  - EEG Beta
  - EEG Parietal Alpha
